//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleNote.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentFolder
    {
        public int FolderId { get; set; }
        public string FolderName { get; set; }
        public Nullable<int> ParentFolderId { get; set; }
    }
}
