using System.ComponentModel;
using System.Xml.Serialization;

namespace BibleNote.Services.ModulesManager.Scheme.ZefaniaXml
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан программой.
    //     Исполняемая версия:2.0.50727.6266
    //
    //     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
    //     повторной генерации кода.
    // </auto-generated>
    //------------------------------------------------------------------------------
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 
    ////////////////////////////////////INFORMATION////////////////////////////////////
    // The schema description is available at http://bgfdb.de/zefaniaxml/bml/index.html
    // was changed:
    //  -added [DefaultValue("")] to VERS.e
    //  -removed VERS.Text, STYLE.Text, GRAM.Text, SUP.Text properties
    //  -added [XmlText(typeof(string))] to VERS.Items, STYLE.Text, GRAM.Text, SUP.Text properties
    //  -added [System.Xml.Serialization.XmlElementAttribute("gr", typeof(gr))] to VERS.Items, STYLE.Text, GRAM.Text, SUP.Text properties
    //  -commented [System.Xml.Serialization.XmlElementAttribute("date", typeof(System.DateTime), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")] at INFORMATION.Items


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class XMLBIBLE
    {

        private INFORMATION iNFORMATIONField;

        private BIBLEBOOK[] bIBLEBOOKField;

        private APPINFO[] aPPINFOField;

        private string biblenameField;

        private ModuleStatus statusField;

        private bool statusFieldSpecified;

        private string versionField;

        private string revisionField;

        private ModuleType typeField;

        public XMLBIBLE()
        {
            this.typeField = ModuleType.xbible;
        }

        /// <remarks/>
        public INFORMATION INFORMATION
        {
            get
            {
                return this.iNFORMATIONField;
            }
            set
            {
                this.iNFORMATIONField = value;
            }
        }

        /// <remarks/>
        [XmlElement("BIBLEBOOK")]
        public BIBLEBOOK[] BIBLEBOOK
        {
            get
            {
                return this.bIBLEBOOKField;
            }
            set
            {
                this.bIBLEBOOKField = value;
            }
        }

        /// <remarks/>
        [XmlElement("APPINFO")]
        public APPINFO[] APPINFO
        {
            get
            {
                return this.aPPINFOField;
            }
            set
            {
                this.aPPINFOField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string biblename
        {
            get
            {
                return this.biblenameField;
            }
            set
            {
                this.biblenameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public ModuleStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "integer")]
        public string revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue(ModuleType.xbible)]
        public ModuleType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class INFORMATION
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        /// <remarks/>
        [XmlElement("contributors", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("coverage", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("creator", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //[System.Xml.Serialization.XmlElementAttribute("date", typeof(System.DateTime), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date")]
        [XmlElement("description", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("format", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("identifier", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("language", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("publisher", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("rights", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("source", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("subject", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("title", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("type", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        contributors,

        /// <remarks/>
        coverage,

        /// <remarks/>
        creator,

        /// <remarks/>
        date,

        /// <remarks/>
        description,

        /// <remarks/>
        format,

        /// <remarks/>
        identifier,

        /// <remarks/>
        language,

        /// <remarks/>
        publisher,

        /// <remarks/>
        rights,

        /// <remarks/>
        source,

        /// <remarks/>
        subject,

        /// <remarks/>
        title,

        /// <remarks/>
        type,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class BIBLEBOOK
    {

        private CHAPTER[] itemsField;

        private string bnumberField;

        private string bnameField;

        private string bsnameField;

        /// <remarks/>
        [XmlElement("CHAPTER")]
        public CHAPTER[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string bnumber
        {
            get
            {
                return this.bnumberField;
            }
            set
            {
                this.bnumberField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string bname
        {
            get
            {
                return this.bnameField;
            }
            set
            {
                this.bnameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string bsname
        {
            get
            {
                return this.bsnameField;
            }
            set
            {
                this.bsnameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class CHAPTER
    {

        private object[] itemsField;

        private string cnumberField;

        /// <remarks/>
        [XmlElement("CAPTION", typeof(CAPTION))]
        [XmlElement("MEDIA", typeof(TMedia))]
        [XmlElement("PROLOG", typeof(PROLOG))]
        [XmlElement("REMARK", typeof(REMARK))]
        [XmlElement("VERS", typeof(VERS))]
        [XmlElement("XREF", typeof(XREF))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string cnumber
        {
            get
            {
                return this.cnumberField;
            }
            set
            {
                this.cnumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class CAPTION
    {

        private object[] itemsField;

        private string[] textField;

        private string vrefField;

        private string countField;

        private CaptionType typeField;

        private bool typeFieldSpecified;

        /// <remarks/>
        [XmlElement("BR", typeof(BR))]
        [XmlElement("GRAM", typeof(GRAM))]
        [XmlElement("STYLE", typeof(STYLE))]
        [XmlElement("SUP", typeof(SUP))]
        [XmlElement("XREF", typeof(XREF))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string vref
        {
            get
            {
                return this.vrefField;
            }
            set
            {
                this.vrefField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public CaptionType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class BR
    {

        private BreakType artField;

        private string countField;

        /// <remarks/>
        [XmlAttribute()]
        public BreakType art
        {
            get
            {
                return this.artField;
            }
            set
            {
                this.artField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum BreakType
    {

        /// <remarks/>
        [XmlEnum("x-nl")]
        xnl,

        /// <remarks/>
        [XmlEnum("x-p")]
        xp,
    }  

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class GRAM
    {
        private object[] itemsField;        

        private string strField;

        private string rmacField;

        /// <remarks/>
        [XmlText(typeof(string))]
        [XmlElement("gr", typeof(gr))]
        [XmlElement("BR", typeof(BR))]        
        [XmlElement("GRAM", typeof(GRAM))]
        [XmlElement("STYLE", typeof(STYLE))]
        [XmlElement("SUP", typeof(SUP))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }       

        /// <remarks/>
        [XmlAttribute()]
        public string str
        {
            get
            {
                return this.strField;
            }
            set
            {
                this.strField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string rmac
        {
            get
            {
                return this.rmacField;
            }
            set
            {
                this.rmacField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class STYLE
    {
        private object[] itemsField;        

        private string cssField;

        private string idField;

        private TStyleFix fsField;

        private bool fsFieldSpecified;

        /// <remarks/>        
        [XmlText(typeof(string))]
        [XmlElement("gr", typeof(gr))]
        [XmlElement("GRAM", typeof(GRAM))]
        [XmlElement("STYLE", typeof(STYLE))]
        [XmlElement("SUP", typeof(SUP))]        
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }        

        /// <remarks/>
        [XmlAttribute()]
        public string css
        {
            get
            {
                return this.cssField;
            }
            set
            {
                this.cssField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public TStyleFix fs
        {
            get
            {
                return this.fsField;
            }
            set
            {
                this.fsField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool fsSpecified
        {
            get
            {
                return this.fsFieldSpecified;
            }
            set
            {
                this.fsFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class SUP
    {
        private object[] itemsField;        

        private SupType artField;

        /// <remarks/>
        [XmlText(typeof(string))]
        [XmlElement("gr", typeof(gr))]
        [XmlElement("GRAM", typeof(GRAM))]
        [XmlElement("STYLE", typeof(STYLE))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }     

        /// <remarks/>
        [XmlAttribute()]
        public SupType art
        {
            get
            {
                return this.artField;
            }
            set
            {
                this.artField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum SupType
    {

        /// <remarks/>
        [XmlEnum("x-sup")]
        xsup,

        /// <remarks/>
        [XmlEnum("x-sub")]
        xsub,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum TStyleFix
    {

        /// <remarks/>
        acrostic,

        /// <remarks/>
        bold,

        /// <remarks/>
        emphasis,

        /// <remarks/>
        illuminated,

        /// <remarks/>
        italic,

        /// <remarks/>
        [XmlEnum("line-through")]
        linethrough,

        /// <remarks/>
        normal,

        /// <remarks/>
        [XmlEnum("small-caps")]
        smallcaps,

        /// <remarks/>
        sub,

        /// <remarks/>
        super,

        /// <remarks/>
        underline,

        /// <remarks/>
        overline,

        /// <remarks/>
        capitalize,

        /// <remarks/>
        uppercase,

        /// <remarks/>
        lowercase,

        /// <remarks/>
        divineName,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class XREF
    {

        private string vefField;

        private string aixField;

        private string fscopeField;

        private string[] textField;

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string vef
        {
            get
            {
                return this.vefField;
            }
            set
            {
                this.vefField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string aix
        {
            get
            {
                return this.aixField;
            }
            set
            {
                this.aixField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string fscope
        {
            get
            {
                return this.fscopeField;
            }
            set
            {
                this.fscopeField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum CaptionType
    {

        /// <remarks/>
        [XmlEnum("x-h1")]
        xh1,

        /// <remarks/>
        [XmlEnum("x-h2")]
        xh2,

        /// <remarks/>
        [XmlEnum("x-h3")]
        xh3,

        /// <remarks/>
        [XmlEnum("x-h4")]
        xh4,

        /// <remarks/>
        [XmlEnum("x-h5")]
        xh5,

        /// <remarks/>
        [XmlEnum("x-h6")]
        xh6,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlRoot("MEDIA", Namespace = "", IsNullable = false)]
    public partial class TMedia
    {

        private string titleField;

        private MediaType typeField;

        private bool typeFieldSpecified;

        /// <remarks/>
        [XmlAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public MediaType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum MediaType
    {

        /// <remarks/>
        [XmlEnum("m-video")]
        mvideo,

        /// <remarks/>
        [XmlEnum("m-audio")]
        maudio,

        /// <remarks/>
        [XmlEnum("m-picture")]
        mpicture,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class PROLOG
    {

        private object[] itemsField;

        private string[] textField;

        private string vrefField;

        /// <remarks/>
        [XmlElement("BR", typeof(BR))]
        [XmlElement("GRAM", typeof(GRAM))]
        [XmlElement("STYLE", typeof(STYLE))]
        [XmlElement("SUP", typeof(SUP))]
        [XmlElement("XREF", typeof(XREF))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string vref
        {
            get
            {
                return this.vrefField;
            }
            set
            {
                this.vrefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class REMARK
    {

        private object[] itemsField;

        private string[] textField;

        private string vrefField;

        private string artField;

        private string aixField;

        /// <remarks/>
        [XmlElement("BR", typeof(BR))]
        [XmlElement("GRAM", typeof(GRAM))]
        [XmlElement("STYLE", typeof(STYLE))]
        [XmlElement("SUP", typeof(SUP))]
        [XmlElement("XREF", typeof(XREF))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string vref
        {
            get
            {
                return this.vrefField;
            }
            set
            {
                this.vrefField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string art
        {
            get
            {
                return this.artField;
            }
            set
            {
                this.artField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string aix
        {
            get
            {
                return this.aixField;
            }
            set
            {
                this.aixField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class VERS
    {

        private object[] itemsField;        

        private string vnumberField;

        private string vField;

        private string eField;

        private string aixField;

        private bool pField;

        private bool pFieldSpecified;

        /// <remarks/>
        [XmlText(typeof(string))]
        [XmlElement("BR", typeof(BR))]
        [XmlElement("gr", typeof(gr))]
        [XmlElement("GRAM", typeof(GRAM))]
        [XmlElement("NOTE", typeof(NOTE))]
        [XmlElement("STYLE", typeof(STYLE))]
        [XmlElement("SUP", typeof(SUP))]
        [XmlElement("XREF", typeof(XREF))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlTextAttribute()]
        //public string[] Text
        //{
        //    get
        //    {
        //        return this.textField;
        //    }
        //    set
        //    {
        //        this.textField = value;
        //    }
        //}

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string vnumber
        {
            get
            {
                return this.vnumberField;
            }
            set
            {
                this.vnumberField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string v
        {
            get
            {
                return this.vField;
            }
            set
            {
                this.vField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [DefaultValue("")]
        public string e
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string aix
        {
            get
            {
                return this.aixField;
            }
            set
            {
                this.aixField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool p
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool pSpecified
        {
            get
            {
                return this.pFieldSpecified;
            }
            set
            {
                this.pFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class NOTE
    {

        private object[] itemsField;

        private string[] textField;

        private TNotesFix typeField;

        private bool typeFieldSpecified;

        private TNotesFix n1Field;

        private bool n1FieldSpecified;

        private TNotesFix n2Field;

        private bool n2FieldSpecified;

        private TNotesFix n3Field;

        private bool n3FieldSpecified;

        private TNotesFix n4Field;

        private bool n4FieldSpecified;

        private TNotesFix n5Field;

        private bool n5FieldSpecified;

        private string exField;

        /// <remarks/>
        [XmlElement("BR", typeof(BR))]
        [XmlElement("GRAM", typeof(GRAM))]
        [XmlElement("STYLE", typeof(STYLE))]
        [XmlElement("SUP", typeof(SUP))]
        [XmlElement("XREF", typeof(XREF))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public TNotesFix type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public TNotesFix n1
        {
            get
            {
                return this.n1Field;
            }
            set
            {
                this.n1Field = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool n1Specified
        {
            get
            {
                return this.n1FieldSpecified;
            }
            set
            {
                this.n1FieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public TNotesFix n2
        {
            get
            {
                return this.n2Field;
            }
            set
            {
                this.n2Field = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool n2Specified
        {
            get
            {
                return this.n2FieldSpecified;
            }
            set
            {
                this.n2FieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public TNotesFix n3
        {
            get
            {
                return this.n3Field;
            }
            set
            {
                this.n3Field = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool n3Specified
        {
            get
            {
                return this.n3FieldSpecified;
            }
            set
            {
                this.n3FieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public TNotesFix n4
        {
            get
            {
                return this.n4Field;
            }
            set
            {
                this.n4Field = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool n4Specified
        {
            get
            {
                return this.n4FieldSpecified;
            }
            set
            {
                this.n4FieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public TNotesFix n5
        {
            get
            {
                return this.n5Field;
            }
            set
            {
                this.n5Field = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool n5Specified
        {
            get
            {
                return this.n5FieldSpecified;
            }
            set
            {
                this.n5FieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string ex
        {
            get
            {
                return this.exField;
            }
            set
            {
                this.exField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum TNotesFix
    {

        /// <remarks/>
        [XmlEnum("x-studynote")]
        xstudynote,

        /// <remarks/>
        [XmlEnum("n-studynote")]
        nstudynote,

        /// <remarks/>
        added,

        /// <remarks/>
        allusion,

        /// <remarks/>
        alternative,

        /// <remarks/>
        background,

        /// <remarks/>
        citation,

        /// <remarks/>
        crossReference,

        /// <remarks/>
        devotional,

        /// <remarks/>
        encoder,

        /// <remarks/>
        exegesis,

        /// <remarks/>
        explanation,

        /// <remarks/>
        liturgical,

        /// <remarks/>
        speaker,

        /// <remarks/>
        study,

        /// <remarks/>
        translation,

        /// <remarks/>
        variant,

        /// <remarks/>
        amplified,

        /// <remarks/>
        changed,

        /// <remarks/>
        deleted,

        /// <remarks/>
        implied,

        /// <remarks/>
        moved,

        /// <remarks/>
        tenseChange,

        /// <remarks/>
        commentary,

        /// <remarks/>
        exposition,

        /// <remarks/>
        meditation,

        /// <remarks/>
        outline,

        /// <remarks/>
        rebuttal,

        /// <remarks/>
        sermon,

        /// <remarks/>
        studyGuide,

        /// <remarks/>
        [XmlEnum("translation")]
        translation1,

        /// <remarks/>
        transChange,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class APPINFO
    {

        private System.Xml.XmlElement anyField;

        private string appidField;

        /// <remarks/>
        [XmlAnyElement()]
        public System.Xml.XmlElement Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string appid
        {
            get
            {
                return this.appidField;
            }
            set
            {
                this.appidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum ModuleStatus
    {

        /// <remarks/>
        v,

        /// <remarks/>
        w,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum ModuleType
    {

        /// <remarks/>
        [XmlEnum("x-bible")]
        xbible,

        /// <remarks/>
        [XmlEnum("x-quran")]
        xquran,

        /// <remarks/>
        [XmlEnum("x-mormon")]
        xmormon,

        /// <remarks/>
        [XmlEnum("x-other")]
        xother,

        /// <remarks/>
        [XmlEnum("x-cult")]
        xcult,
    }

}
