// <auto-generated />
using System;
using BibleNote.Analytics.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BibleNote.Analytics.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsContext))]
    partial class AnalyticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DocumentFolderId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<decimal>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("DocumentFolderId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.DocumentFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NavigationProviderName")
                        .IsRequired();

                    b.Property<int?>("ParentFolderId");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("DocumentFolders");
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.DocumentParagraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DocumentId");

                    b.Property<int>("Index");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentParagraphs");
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.VerseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DocumentParagraphId");

                    b.Property<string>("Suffix");

                    b.Property<long>("VerseId");

                    b.Property<decimal>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("DocumentParagraphId");

                    b.ToTable("VerseEntries");
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.VerseRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DocumentParagraphId");

                    b.Property<decimal>("RelationWeight");

                    b.Property<int?>("RelativeDocumentParagraphId");

                    b.Property<long>("RelativeVerseId");

                    b.Property<long>("VerseId");

                    b.HasKey("Id");

                    b.HasIndex("DocumentParagraphId");

                    b.HasIndex("RelativeDocumentParagraphId");

                    b.HasIndex("RelativeVerseId");

                    b.HasIndex("VerseId");

                    b.ToTable("VerseRelations");
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.Document", b =>
                {
                    b.HasOne("BibleNote.Analytics.Domain.Entities.DocumentFolder", "Folder")
                        .WithMany()
                        .HasForeignKey("DocumentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.DocumentFolder", b =>
                {
                    b.HasOne("BibleNote.Analytics.Domain.Entities.DocumentFolder", "ParentFolder")
                        .WithMany()
                        .HasForeignKey("ParentFolderId");
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.DocumentParagraph", b =>
                {
                    b.HasOne("BibleNote.Analytics.Domain.Entities.Document", "Document")
                        .WithMany("Paragraphs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.VerseEntry", b =>
                {
                    b.HasOne("BibleNote.Analytics.Domain.Entities.DocumentParagraph", "DocumentParagraph")
                        .WithMany()
                        .HasForeignKey("DocumentParagraphId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BibleNote.Analytics.Domain.Entities.VerseRelation", b =>
                {
                    b.HasOne("BibleNote.Analytics.Domain.Entities.DocumentParagraph", "DocumentParagraph")
                        .WithMany()
                        .HasForeignKey("DocumentParagraphId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BibleNote.Analytics.Domain.Entities.DocumentParagraph", "RelativeDocumentParagraph")
                        .WithMany()
                        .HasForeignKey("RelativeDocumentParagraphId");
                });
#pragma warning restore 612, 618
        }
    }
}
